import React from 'react'
import {Icon} from 'react-native-elements';
import {View} from 'react-native'
export default class Icons extends React.Component{
render(){
    return(  
        <View>
        <Icon
        reverse
        name='ios-american-football'
        type='ionicon'
        color='black'
      />
      <Icon
        reverse
        name='ios-car'
        type='ionicon'
        color='black'
      />
      <Icon
        reverse
        name='ios-airplane'
        type='ionicon'
        color='black'
      />
      <Icon
        reverse
        name='ios-laptop'
        type='ionicon'
        color='black'
      />
      <Icon
        reverse
        name='ios-umbrella'
        type='ionicon'
        color='black'
      />
      <Icon
        reverse
        name='ios-car'
        type='ionicon'
        color='black'
      />
      <Icon
        reverse
        name='ios-tablet-portrait'
        type='ionicon'
        color='black'
      />
      <Icon
        reverse
        name='ios-subway'
        type='ionicon'
        color='black'
      />
      </View>
    )
}
}